language: java
jdk:
  - oraclejdk7
  - openjdk7
  - openjdk6
install: true
script: ./gradlew -PkeystoreFile=none -PkeystoreKeyAlias=none -PkeystoreStorePassword=none -PkeystoreKeyPassword=none model:test

